### ISSUE TITLE
pipeline fails in job `release`

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#33]
```
[4:47:48 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[4:47:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[4:47:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[4:47:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[4:47:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-docker"
[4:47:48 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "semantic-release-docker"
[4:47:48 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Environment variable DOCKER_USERNAME is not set
    at module.exports (/usr/local/lib/node_modules/semantic-release-docker/lib/verify.js:6:13)
    at validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/usr/local/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  pluginName: 'semantic-release-docker'
}
AggregateError: 
    Error: Environment variable DOCKER_USERNAME is not set
        at module.exports (/usr/local/lib/node_modules/semantic-release-docker/lib/verify.js:6:13)
        at validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/usr/local/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/usr/local/lib/node_modules/semantic-release/index.js:94:3)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:259:22)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}
```

**Comment by fforootd** [comment]
I have a look into this

**Comment by fforootd** [comment]
muss ich nochmals anschauen
